packages:
  - apps/*
  - packages/*

catalog:
  "typescript": "^5.9.3"
  "valibot": "^1.2.0"
  "valibot-env": "^1.0.0"
  "drizzle-orm": "^0.45.1"
  "postgres": "3.4.7"
  "@types/pg": "^8.16.0"
  "drizzle-kit": "^0.31.8"
  "tsx": "^4.21.0"

  "better-auth": "^1.4.0"

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp
